---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-component
  annotations:
    github.com/project-slug: AcmeInc/replicate-entity-deletion-issue
spec:
  type: service
  lifecycle: production
  owner: engineering
